name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # (opțional) debug că secretul există
      - name: Debug token presence
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "Token EMPTY"; exit 1; 
          else
            echo "Token present";
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"                          # rădăcina proiectului
          api_location: ""                           # gol dacă nu ai API
          output_location: "dist/dorius-landing/browser"  # ce iese din ng build
